#!/bin/bash

project=$(basename `pwd`)

if [[ $# = 0 ]] ; then
    refname=$(git symbolic-ref HEAD 2>/dev/null)
    merged=$(git rev-parse HEAD)
else
    refname=$1
    merged=$2
fi

refname=${refname##refs/heads/}

gitver=$(git --version)
gitver=${gitver##* }

rev=$(git log ${merged} -n 1 --oneline | awk '{print $1}' 2>/dev/null)
[[ -z ${rev} ]] && rev=${merged:0:12}

rawcommit=$(git cat-file commit ${merged})

author=$(echo "${rawcommit}" | grep author | awk '{print $2}')

logmessage=$(sed -e '1,/^$/d' <<< "${rawcommit}")
logmessage_count=$(wc -l <<< "${logmessage}")

ts=$(sed -n -e '/^author .*> \([0-9]\+\).*$/s--\1-p' \
    <<< "${rawcommit}")

files=$(git diff-tree -r --name-only ${merged} |
    sed -e '1d' -e 's-.*-&-')

url="https://git.yeahunter.hu/?p=${project};a=commitdiff;h=@@sha1@@"

#bitly=$(./hooks/yhsteu.pl ${url//@@sha1@@/${merged}}) #Majd kesobb ha mar stabil lesz.
bitly=${url//@@sha1@@/${merged}}

mono /home/peti/IRCBOT/FBI-server/Run/Release/Client.exe --host=127.0.0.1 --port=35220 --password=AbasslUIO883jHHG --author=${author} --url=${bitly} --project=${project} --refname=${refname} --rev=${rev} --channels=#dev --ircserver=default --message=${logmessage}
