#!/bin/bash
refname=$1
oldhead=$2
newhead=$3

#if [ "$oldhead" -eq 0 ]; then
    # list everything reachable from newrev but not any heads
#list=git rev-list $(git for-each-ref --format='%(refname)' "refs/heads/*" | sed 's/^/\^/') "$newhead"
#else
#list=$(git rev-list ${oldhead}..${newhead} | tac)
##fi

for merged in $(git rev-list ${oldhead}..${newhead} | tac) ; do
    ./hooks/fbi ${refname} ${merged}
done
